In [1]:
import numpy as np

In [ ]:
my_array = np.array([1, 2, 3, 4, 5])
# print(my_array)

# shape retorna uma tupla que indica as dimenções do array.
# print(my_array.shape)

my_array = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
# print(my_array.shape)
# retorna que temos 2 dimenções com 5 elementos.

In [ ]:
# np.arange, criar um array com valoes uniformemente distribuidos dentro do intervalo
# np.range(start, stop, step, dtype=None)
my_array = np.arange(1, 10)
# print(my_array)

#reshap para redimensionar o array
a = np.arange(10).reshape((2, 5))
# print(a)
b = np.array([[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3],
          [1, 2, 3],
          [1, 2, 3],
          [1, 2, 3],]).reshape((3, 6))
# print(b)

In [ ]:
lst = [1, 2, 3.8, 4, 5, 6.4, 7.1, 8, 9 ]
v = np.array(lst)
v = v * 2
# print(v)

my_array = np.full((3, 3), True)
# print(my_array)

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
# print(a[[0, 1, 2], [0, 1, 0]])
# print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

# print(a[[0, 0], [1, 1]])
# print(np.array([a[0, 1], a[0, 1]]))

In [ ]:
#Cria um novo array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
#Cria um array de index
b = np.array([0, 2, 0, 1])
#é selecionado um elemento de cada linha usando os indices b
# print(a[np.arange(4), b])
#Muda o valor dos elementos de cada linha usando os indeces de b
a[np.arange(4), b] += 10
# print(a)

In [ ]:
#cria um novo array.E encontra os elementos que são maiores que 2, retornando um array bool
bool_idx = (a>2)
# print(bool_idx)
#Cria um array com os elementos correspondentes com valores True no array anterior
# print(a[bool_idx])
#Mesma cois que anteriormente mas de outra forma
# print(a[a>2])

In [ ]:
#Retorna o tipo do array
# print(a.dtype) 
#force esse array a se tornar um int
x = np.array([1.4, 2], dtype= np.int64)
# print(x)

b = a[a % 2 != 0]
# print(b)

#substitui todos os elementos impares do array a por -1
a[a % 2 != 0] = -1
# print(a)

In [ ]:
x = np.array([[1, 2], [3, 4]], dtype= np.float64)
y = np.array([[5, 6], [7, 8]], dtype= np.float64)

# print(x+y)
# print(np.add(x, y))

# print(x-y)
# print(np.subtract(x, y))

# print(x*y)
# print(np.multiply(x, y))

# print(x/y)
# print(np.divide(x, y))

# print(np.sqrt(x))

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# print(v.dot(w))
# print(np.dot(v, w))

# print(w.dot(v))
# print(np.dot(w, v))

# print(x.dot(y))
# print(np.dot(x, y))

In [ ]:
x = np.array([[1, 2, 3], 
              [2, 2, 2], 
              [3, 3, 3]])

y = np.array([[3, 2, 1], 
              [1, 2, 3], 
              [-1, -2, -3]])
r = x * y
# print(r)

ma = np.mat(x)
mb = np.mat(y)
r = ma * mb
# print(r)


In [ ]:
# print(np.sum(x)) # soma a matrix
# print(np.sum(x, axis=0)) #soma as colunas
# print(np.sum(x, axis=1)) #soma as linhas

# print(x.T) # transpor uma matriz, transformar as linhas em colunas

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 6, 8], [9, 10, 11]])
v = np.array([1, 0, 1])
print(x)

#cria um array igual ao array x
y = np.empty_like(x)

for i in range(4):
    y[i,:] = x[i,:] + v
#realiza 4 vezes, por ser 4 linhas, soma v na matrix x
print(y)

In [8]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 6, 8], [9, 10, 11]])
v = np.array([1, 0, 1])
vv = np.tile( v, (4, 1))
# Primeira dimensão (4): indica que o array v será repetido 4 vezes ao longo das linhas.
# Segunda dimensão (1): indica que o array v será repetido 1 vez ao longo das colunas.
print(vv)

y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  6  9]
 [10 10 12]]


In [9]:
a = np.floor(10 * np.random.random((3, 4)))
print(a)
# a função floor limita para que os numeros gerados pelo random sejam inteiros
x = True
y =  False
print(np.where(a>2, x, y))
#a função retonara x caso a condição for verdadeira e y para quando for falsa

[[7. 4. 7. 6.]
 [8. 3. 6. 7.]
 [0. 7. 9. 9.]]
[[ True  True  True  True]
 [ True  True  True  True]
 [False  True  True  True]]


In [11]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.where(x % 2 != 0, -1, x))

[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


In [14]:

#criar arrays com valores espaçados
print(np.linspace(1, 10)) #1: valor inicial. 10: valor final.
#O comportamento padrão do np.linspace é gerar 50 valores quando o número de elementos não é especificado.
print(np.linspace(1, 10, 7)) #número de valores que você quer gerar.
print(np.linspace(1, 10, 7, endpoint=False)) #significa que o valor 10 será excluído do array.

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]
